name: oss_flutter
description: Aliyun Oss Client for flutter.
version: 0.1.5
author: Alexander.Li<superpowerlee@gmail.com>
homepage: https://github.com/ipconfiger/oss_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  intl: any
  xml: ^5.3.1


dev_dependencies:
  test: '>=0.12.30 <1.4.0'
  http_client: ^1.4.2
